// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0jps54s9qEuv7O6X_zn-vo9-TqTD04gY',
    appId: '1:861013440558:web:846c3be65436f1ed6007bf',
    messagingSenderId: '861013440558',
    projectId: 'sat-project-187',
    authDomain: 'sat-project-187.firebaseapp.com',
    storageBucket: 'sat-project-187.firebasestorage.app',
    measurementId: 'G-32YNKBNFDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCszALdknfXAEl2G4mqV7JPuKSslYTen_0',
    appId: '1:861013440558:android:46dbb9909b9851386007bf',
    messagingSenderId: '861013440558',
    projectId: 'sat-project-187',
    storageBucket: 'sat-project-187.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXHELMhT7hzEm6KF74JnSfxEhh5PHCXJM',
    appId: '1:861013440558:ios:0d540f270a096efd6007bf',
    messagingSenderId: '861013440558',
    projectId: 'sat-project-187',
    storageBucket: 'sat-project-187.firebasestorage.app',
    iosClientId: '861013440558-5r8oopn0th2lejis2vaphhiv82blm98t.apps.googleusercontent.com',
    iosBundleId: 'com.example.satPracticeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXHELMhT7hzEm6KF74JnSfxEhh5PHCXJM',
    appId: '1:861013440558:ios:0d540f270a096efd6007bf',
    messagingSenderId: '861013440558',
    projectId: 'sat-project-187',
    storageBucket: 'sat-project-187.firebasestorage.app',
    iosClientId: '861013440558-5r8oopn0th2lejis2vaphhiv82blm98t.apps.googleusercontent.com',
    iosBundleId: 'com.example.satPracticeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0jps54s9qEuv7O6X_zn-vo9-TqTD04gY',
    appId: '1:861013440558:web:9f206dd33034a2ca6007bf',
    messagingSenderId: '861013440558',
    projectId: 'sat-project-187',
    authDomain: 'sat-project-187.firebaseapp.com',
    storageBucket: 'sat-project-187.firebasestorage.app',
    measurementId: 'G-C5SP3EM61F',
  );
}
